development:
  adapter: postgresql
  encoding: unicode
  database: ItascaISDLessons-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ItascaISDLessons-test
  pool: 5
  port: 5432
  host: localhost